// Jenkinsfile for Api-users - 
// Set the tag for the development image: version + build number
def devTag      = "0.0.0"

// Set the tag for the production image: version
def prodTag     = "0.0.0"
def artifactVersion
def artifactName	= ""
def destApp = "" 
def activeApp = ""

node() {
  properties([
      parameters(
          [
            string(name: 'namespace', defaultValue: 'dev-admin-users', description:'Nombre del proyecto en Openshift'),
            string(name: 'appName', defaultValue: 'api-users', description:'Application name')
          ]
        )
  ])

  echo "Namespace: ${params.namespace}"
  echo "Application name: ${params.appName}"

  //Stage de Preparación y configuración de herramientas
  stage('Preparing'){

    //Herramienta de Maven
		mvnHome = tool 'M2'
		mvnCmd = "${mvnHome}/bin/mvn "

    //Definición Jdk
		env.JAVA_HOME=tool 'JDK18'
		env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
		sh 'java -version'
	}

   // Stage descarga código fuente y leer variables del pom
  stage('Checkout Source') {
	  checkout scm  
    dir("backend-users"){
      //Obtener version y el nombre del artefacto 
      def pom = readMavenPom file: 'pom.xml'
      artifactVersion = pom.version
      artifactName = pom.artifactId
      echo "La version del artefacto es: "+artifactVersion; 
      echo "El nombre de artefacto es: "+artifactName; 

      devTag  = "${artifactVersion}-" + currentBuild.number
      echo "Versión de la imagen Devtag: ${devTag}"
    }
	        	
  }

}
