// Jenkinsfile for Api-users - 
// Set the tag for the development image: version + build number
def devTag      = "0.0-0"

// Set the tag for the production image: version
def prodTag     = "0.0"

def version

def artifact	= ""
def destApp = "" 
def activeApp = ""




pipeline {
    agent any
    stages {
      stage('Preparing'){
       


          }

            // Checkout Source Code
    stage('Checkout Source') {

      steps {
        checkout scm  
        dir("complete/backend-users"){
          def pom = 'pom.xml'
          version = getVersionFromPom(pom)
          echo version;

          devTag  = "${version}-" + currentBuild.number
          artifact = getArtifactIdFromPom(pom)	    	
        }	    
        echo "Devtag: ${devTag}"
      }      	
    }
    //end of the checkout stage
    


    }
}

// Convenience Functions to read variables from the pom.xml
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}